/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author LABRPL 14
 */

public class gaji extends javax.swing.JFrame {
    /**
     * Creates new form gaji
     */
     
    
    String gaji;
    int[] gj = {10000000,7000000,2500000,1700000};
    public gaji() {
        initComponents();
//          String stringConn = "jdbc:mysql://localhost/data_pegawai";
//        try{
//           Class.forName("com.mysql.jdbc.Driver");
//           conn = (Connection)DriverManager.getConnection(stringConn,"root","");
//           stmt = conn.createStatement();
//        }catch(Exception e){
//           System.err.println(e);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        pilih = new javax.swing.JComboBox<String>();
        gaji_pokok = new javax.swing.JTextField();
        kontrak = new javax.swing.JRadioButton();
        tetap = new javax.swing.JRadioButton();
        tunjangan = new javax.swing.JTextField();
        pajak = new javax.swing.JTextField();
        totgaji = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nip = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("FORM PENGHITUNGAN GAJI");

        jLabel2.setText("Nama");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Gaji Pokok");

        jLabel5.setText("Status");

        jLabel6.setText("Tunjangan");

        jLabel7.setText("Pajak(15%)");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Gaji");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("Bersih");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pilih.setForeground(new java.awt.Color(255, 0, 255));
        pilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direktur", "Manajer", "Staff", "Administrasi" }));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        gaji_pokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaji_pokokActionPerformed(evt);
            }
        });

        kontrak.setText("Kontrak");
        kontrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontrakActionPerformed(evt);
            }
        });

        tetap.setText("Tetap");
        tetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tetapActionPerformed(evt);
            }
        });

        tunjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanganActionPerformed(evt);
            }
        });

        pajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pajakActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setForeground(new java.awt.Color(0, 0, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setForeground(new java.awt.Color(0, 0, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setForeground(new java.awt.Color(255, 0, 51));
        btnHapus.setText("hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setForeground(new java.awt.Color(153, 153, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel9.setText("NIP");

        nip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nipActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(84, 84, 84)
                .addComponent(jButton3)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kontrak)
                            .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(pilih, 0, 180, Short.MAX_VALUE)
                            .addComponent(gaji_pokok, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tetap)
                            .addComponent(tunjangan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(pajak, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(totgaji, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(nip)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(hitung)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gaji_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(kontrak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tetap)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hitung)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnSimpan))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        int a = Integer.parseInt(pajak.getText());
        int b = Integer.parseInt(gaji_pokok.getText());
        int c = Integer.parseInt(tunjangan.getText());
        int d = (b + c) - a;
        totgaji.setText(Integer.toString(d));
        totgaji.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        
        if(pilih.getSelectedItem() == "Direktur"){
            gaji_pokok.setText(Integer.toString(gj[0]));
            gaji_pokok.setEditable(false);
        }
        if(pilih.getSelectedItem() == "Manajer"){
            gaji_pokok.setText(Integer.toString(gj[1]));
            gaji_pokok.setEditable(false);
        }
        if(pilih.getSelectedItem() == "Staff"){
            gaji_pokok.setText(Integer.toString(gj[2]));
            gaji_pokok.setEditable(false);
        }
        if(pilih.getSelectedItem() == "Administrasi"){
            gaji_pokok.setText(Integer.toString(gj[3]));
            gaji_pokok.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihActionPerformed

    private void gaji_pokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaji_pokokActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_gaji_pokokActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pajakActionPerformed
        
        //pajak.setText((gaji_pokok + tunjangan)*(15/100));
        // TODO add your handling code here:
    }//GEN-LAST:event_pajakActionPerformed

    private void tunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanganActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_tunjanganActionPerformed

    private void kontrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontrakActionPerformed
        // TODO add your handling code here:
        if(pilih.getSelectedItem() == "Staff"){
            tunjangan.setText(Integer.toString(gj[2] * 25/100));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString((gj[2] + gj[2]*25/100) * 15/100));
            pajak.setEditable(false);
        }
        
        else if(pilih.getSelectedItem() == "Administrasi"){
            tunjangan.setText(Integer.toString(gj[3] * 15/100));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString((gj[3] + gj[3]*15/100) * 15/100));
            pajak.setEditable(false);
        }
        else{
            int x = 0;
            tunjangan.setText(Integer.toString(x));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString(x));
            pajak.setEditable(false);
        }
    }//GEN-LAST:event_kontrakActionPerformed

    private void tetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tetapActionPerformed
        if(pilih.getSelectedItem() == "Direktur"){
            tunjangan.setText(Integer.toString(gj[0] * 75/100));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString((gj[0] + gj[0]*75/100) * 15/100));
            pajak.setEditable(false);
        }
        else if(pilih.getSelectedItem() == "Manajer"){
            tunjangan.setText(Integer.toString(gj[1] * 50/100));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString((gj[1] + gj[1]*50/100) * 15/100));
            pajak.setEditable(false);
        }
        else{
            int x = 0;
            tunjangan.setText(Integer.toString(x));
            tunjangan.setEditable(false);
            pajak.setText(Integer.toString(x));
            pajak.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tetapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nip.setText("");
        txtnama.setText("");
        pilih.setSelectedIndex(0);
        gaji_pokok.setText("");
        tunjangan.setText("");
        pajak.setText("");
        totgaji.setText("");
        kontrak.setSelected(false);
        tetap.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            String vid = (String) nip.getText();
            String vnama = (String) txtnama.getText();
            String vjabatan = (String) pilih.getSelectedItem();
            String vpajak = (String) pajak.getText();
            String vgaji = (String) gaji_pokok.getText();
            String vtunj = (String) tunjangan.getText();
            String vtotgaji = (String) totgaji.getText();
            String vstatus = "";
            if(kontrak.isSelected() == true)
                vstatus = kontrak.getText();
            if(tetap.isSelected() == true)
                vstatus = tetap.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            String stringConn = "jdbc:mysql://localhost/data_pegawai";
            Connection connection =DriverManager.getConnection(stringConn,"root","");
            Statement statement = connection.createStatement();    
            String sql = "INSERT INTO tbl_pegawai VALUES('"+vid+"' ,'"+vnama+"' ,'"+vjabatan+"' ,'"+vgaji+"' , '"+vstatus+"', '"+vtunj+"' , '"+vpajak+"' ,  '"+vtotgaji+"')";
            statement.executeUpdate(sql);
            statement.close();
            connection.close();
            
            JOptionPane.showMessageDialog(null , "Berhasil disimpan");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null , "Data Gagal disimpan");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    try{
        String cnip = nip.getText();
        Class.forName("com.mysql.jdbc.Driver");
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost/data_pegawai","root","");
        Statement statement = connection.createStatement();
        String sql = "SELECT * FROM tbl_pegawai WHERE nip = '"+cnip+"'";
        ResultSet rs = statement.executeQuery(sql);
            
        //Menghasilkan setelan
        if(rs.next()){
            nip.setText(rs.getString(1));
            txtnama.setText(rs.getString(2));
            pilih.setSelectedItem(rs.getString(3));
            gaji_pokok.setText(rs.getString(4));
            String vstatus;
            vstatus = rs.getString(5);
            if(vstatus.equals("kontrak"))
                kontrak.setSelected(true);
            if(vstatus.equals("tetap"))
                tetap.setSelected(true);
            tunjangan.setText(rs.getString(6));
            pajak.setText(rs.getString(7));
            totgaji.setText(rs.getString(8));
            nip.requestFocus();
            
                        
        }else{
            JOptionPane.showMessageDialog(null,"Data tidak tersedia");
        }
        statement.close();
        connection.close();
    }catch(Exception e){
        System.out.println("error" +e);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
            String cnip = nip.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection =DriverManager.getConnection("jdbc:mysql://localhost/data_pegawai","root","");
            Statement statement = connection.createStatement();
            String sql = "DELETE FROM tbl_pegawai WHERE nip = '"+cnip+"'";
            statement.executeUpdate(sql);
            statement.close();
            connection.close();
            JOptionPane.showMessageDialog(null,"Data Sudah Dihapus");
            nip.setText("");
            txtnama.setText("");
            gaji_pokok.setText("");
            tunjangan.setText("");
            pajak.setText("");
            totgaji.setText("");
            kontrak.setSelected(false);
            tetap.setSelected(false);
            
            nip.requestFocus();
        }catch(Exception e){
            System.out.println("error" +e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            String tnip = nip.getText();
            String tnama = (String) txtnama.getText();
            String tjabatan = (String) pilih.getSelectedItem();
            String tgaji = (String) gaji_pokok.getText();
            
            String tstatus= (String) "";
            if(kontrak.isSelected() == true)
                 tstatus = kontrak.getText();
             if(tetap.isSelected() == true)
                tstatus = tetap.getText();
          
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection =DriverManager.getConnection("jdbc:mysql://localhost/data_pegawai","root","");
            Statement statement = connection.createStatement();
            String sql = "UPDATE tbl_pegawai SET nama='"+tnama+"' ,jabatan='"+tjabatan+"' , gaji_pokok='"+tgaji+"' , status='"+tstatus+"' WHERE nip='"+tnip+"'";
            
            statement.executeUpdate(sql);
            statement.close();
            connection.close();
            JOptionPane.showMessageDialog(null , "Data berhasil di Edit");
        }catch(Exception e){
           System.out.println("Error" +e); 
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void nipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField gaji_pokok;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton kontrak;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField pajak;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JRadioButton tetap;
    private javax.swing.JTextField totgaji;
    private javax.swing.JTextField tunjangan;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
